In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
import numpy as np
import pandas as pd
import datetime as dt
import os

#Load Data

In [20]:
cd 'C:\Users\dsi\Documents\Python Scripts\data'

C:\Users\gzou\Documents\MktQA_data

In [ ]:
data = {d:}

In [21]:
move_days = ['1','3','5','10','20','40','60']

Move = {}
decile_col = ['#obs']

for day in move_days:
    exec('Move[' + day + ']' + '=pd.DataFrame.from_csv(\'Move' + day + '.csv\')')
    decile_col.append(day)

In [23]:
Price = pd.DataFrame.from_csv('Price.csv')
# HighPrice = pd.DataFrame.from_csv('HighPrice.csv')
# LowPrice = pd.DataFrame.from_csv('LowPrice.csv')
# Volume = pd.DataFrame.from_csv('Volume.csv')
Mkt_Cap = pd.DataFrame.from_csv('MktCap.csv')

In [30]:
Move[1]

,1-800 CONTACTS,1-800-FLOWERS.COM 'A',1ST SOURCE,1ST UNITED BANCORP,1ST.AMER.TENNESSEE,1ST.CHARTER FINL.,1ST.COML.,1ST.ETN.,1ST.FINL.WI.,1ST.INTERSTATE BANCORP,...,ZORAN,ZS PHARMA,ZULILY CLASS A,ZUMIEZ,ZURICH REIN.CTR.,ZURN,ZYGO,ZYMOGENETICS,ZYNGA 'A',ZYTEC
Date,,,,,,,,,,,,,,,,,,,,,
1975-01-02,NaN,NaN,NaN,NaN,NaN,-2.500,NaN,NaN,NaN,4.580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-03,NaN,NaN,NaN,NaN,NaN,1.282,NaN,NaN,NaN,3.650,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-06,NaN,NaN,NaN,NaN,NaN,2.532,NaN,NaN,NaN,1.408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-07,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,1.389,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-08,NaN,NaN,NaN,NaN,NaN,7.407,NaN,NaN,NaN,-1.370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-09,NaN,NaN,NaN,NaN,NaN,3.448,NaN,NaN,NaN,4.167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-10,NaN,NaN,NaN,NaN,NaN,-6.667,NaN,NaN,NaN,1.333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-13,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,-1.316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-14,NaN,NaN,NaN,NaN,NaN,2.381,NaN,NaN,NaN,1.333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-15,NaN,NaN,NaN,NaN,NaN,1.163,NaN,NaN,NaN,0.658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-16,NaN,NaN,NaN,NaN,NaN,-1.149,NaN,NaN,NaN,3.268,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-17,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,0.633,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-20,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,2.516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-21,NaN,NaN,NaN,NaN,NaN,1.163,NaN,NaN,NaN,-1.840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-22,NaN,NaN,NaN,NaN,NaN,-4.598,NaN,NaN,NaN,1.250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-23,NaN,NaN,NaN,NaN,NaN,2.410,NaN,NaN,NaN,1.235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-24,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,3.659,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-27,NaN,NaN,NaN,NaN,NaN,-4.706,NaN,NaN,NaN,1.176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-28,NaN,NaN,NaN,NaN,NaN,14.815,NaN,NaN,NaN,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-29,NaN,NaN,NaN,NaN,NaN,6.452,NaN,NaN,NaN,1.744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-30,NaN,NaN,NaN,NaN,NaN,-1.010,NaN,NaN,NaN,-0.571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-01-31,NaN,NaN,NaN,NaN,NaN,1.020,NaN,NaN,NaN,1.149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-03,NaN,NaN,NaN,NaN,NaN,-4.040,NaN,NaN,NaN,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-04,NaN,NaN,NaN,NaN,NaN,4.211,NaN,NaN,NaN,2.841,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-05,NaN,NaN,NaN,NaN,NaN,-3.030,NaN,NaN,NaN,1.657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-06,NaN,NaN,NaN,NaN,NaN,-3.125,NaN,NaN,NaN,-1.630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-07,NaN,NaN,NaN,NaN,NaN,-4.301,NaN,NaN,NaN,-3.867,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-10,NaN,NaN,NaN,NaN,NaN,-2.247,NaN,NaN,NaN,-1.149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-11,NaN,NaN,NaN,NaN,NaN,3.448,NaN,NaN,NaN,2.326,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975-02-12,NaN,NaN,NaN,NaN,NaN,6.667,NaN,NaN,NaN,3.409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-05-15,NaN,0.000,0.317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.402,-0.222,2.553,NaN,NaN,NaN,NaN,-2.623,NaN
2015-05-18,NaN,-1.213,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.648,-0.297,-2.584,NaN,NaN,NaN,NaN,1.010,NaN
2015-05-19,NaN,-0.307,-0.503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.790,-1.116,-0.129,NaN,NaN,NaN,NaN,-1.333,NaN
2015-05-20,NaN,-0.411,-0.095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.613,0.376,-0.389,NaN,NaN,NaN,NaN,0.338,NaN
2015-05-21,NaN,0.773,-0.063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.549,0.300,-0.618,NaN,NaN,NaN,NaN,-1.347,NaN
2015-05-22,NaN,-0.153,-0.443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.657,-1.495,-1.538,NaN,NaN,NaN,NaN,-2.730,NaN
2015-05-26,NaN,1.025,2.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.328,0.228,0.100,NaN,NaN,NaN,NaN,0.351,NaN
2015-05-27,NaN,-1.420,-1.205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-2.005,0.076,0.564,NaN,NaN,NaN,NaN,2.797,NaN
2015-05-28,NaN,-2.160,-1.251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-1.911,0.038,-1.420,NaN,NaN,NaN,NaN,0.340,NaN
2015-05-29,NaN,1.367,0.095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-2.051,-1.474,-1.373,NaN,NaN,NaN,NaN,-0.339,NaN
2015-06-01,NaN,-1.452,1.424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-1.222,4.835,-0.238,NaN,NaN,NaN,NaN,1.361,NaN
2015-06-02,NaN,3.053,1.528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.035,0.403,1.770,NaN,NaN,NaN,NaN,2.013,NaN
2015-06-03,NaN,-1.634,-1.290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.466,-0.401,-0.535,NaN,NaN,NaN,NaN,-0.658,NaN
2015-06-04,NaN,-0.312,2.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.923,-0.220,-19.301,NaN,NaN,NaN,NaN,1.325,NaN
2015-06-05,NaN,1.562,-0.152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-1.914,-1.467,-0.708,NaN,NaN,NaN,NaN,-2.288,NaN
2015-06-08,NaN,1.231,0.701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.668,-0.223,-0.923,NaN,NaN,NaN,NaN,-0.334,NaN
2015-06-09,NaN,3.242,1.634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.071,2.985,0.381,NaN,NaN,NaN,NaN,1.007,NaN
2015-06-10,NaN,-2.355,0.596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.632,-1.884,-0.084,NaN,NaN,NaN,NaN,-0.664,NaN
2015-06-11,NaN,0.000,-0.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-6.513,3.840,3.801,NaN,NaN,NaN,NaN,1.672,NaN
2015-06-12,NaN,1.608,0.536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.439,3.912,-0.936,NaN,NaN,NaN,NaN,-1.645,NaN
2015-06-15,NaN,0.099,1.274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.900,-0.068,1.232,NaN,NaN,NaN,NaN,-1.338,NaN
2015-06-16,NaN,1.482,-1.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.511,0.479,0.446,NaN,NaN,NaN,NaN,0.339,NaN
2015-06-17,NaN,4.284,1.098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.359,2.045,4.079,NaN,NaN,NaN,NaN,1.014,NaN
2015-06-18,NaN,-1.120,0.411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-2.645,-3.607,2.095,NaN,NaN,NaN,NaN,0.000,NaN
2015-06-19,NaN,-1.889,0.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.980,-2.356,3.725,NaN,NaN,NaN,NaN,-0.334,NaN
2015-06-22,NaN,0.962,1.279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.659,1.490,2.822,NaN,NaN,NaN,NaN,-0.671,NaN
2015-06-23,NaN,0.191,-1.062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-3.298,-1.783,-1.461,NaN,NaN,NaN,NaN,0.676,NaN
2015-06-24,NaN,-0.666,0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.667,-0.142,0.217,NaN,NaN,NaN,NaN,0.336,NaN
2015-06-25,NaN,-0.575,0.551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-2.536,-2.888,-0.217,NaN,NaN,NaN,NaN,-1.672,NaN
2015-06-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Indicator Function

In [22]:
indicator_name = 'some_indic'

def indicatorFun(df,window):
    #price
    return pd.rolling_mean(df,window, 1)

#Parameter

In [24]:
d1 = dt.datetime(2000,1,1)
d2 = dt.datetime(2005,1,1)
d3 = dt.datetime(2010,1,1)

dates = [d1,d2,d3]


window_range = [14, 30, 60, 80, 120, 250] 
cap_range = [250, 1000, 2000, 10000, 50000, inf] 

decades = []
for i in range(len(dates) + 1):
    if i == len(dates):
        decades.append('All Time')
    elif i == len(dates) -1:
        decades.append(str(dates[i])[:4] + '-present')
    else:
        decades.append(str(dates[i])[:4] + '-' + str(dates[i+1].year - 1))

In [25]:
decades

['2000-2004', '2005-2009', '2010-present', 'All Time']

#Output Directory

In [26]:
myPath = r'C:\Users\gzou\Documents\research results/'
myFolder = 'some_indic'

myDirect = myPath+myFolder

if not os.path.isdir(myDirect):
    os.makedirs(myDirect)

#Decile Run

In [ ]:

for window in window_range:
   
    decile_dict = dict.fromkeys(cap_range[:-1])
    for key in decile_dict.keys():
        decile_dict[key] = dict.fromkeys(decades)
   
    
    # calculate indicator table
    
    stoch_table =  indicatorFun(Price,window)
    
    
   
    all_idx = stoch_table.index
   
    max_value = (stoch_table.max().max())*1.01
   
    
    for dates_key in range(len(dates)):
       
        # selected data within period
        #____________________________________________________________________________________________________________________
        
        if (dates_key < (len(dates)-1)):
            sel_idx = all_idx[(all_idx >= dates[dates_key]) & (all_idx < dates[dates_key+1])]
        else:
            sel_idx = all_idx[all_idx >= dates[dates_key]]
 

        Stoch_by_decades = stoch_table.loc[sel_idx]
        Mkt_by_decades = Mkt_Cap.loc[sel_idx]
        for day in move_days:
            exec('Move' + day + '_by_decades = Move[' + day + '].loc[sel_idx]')
        
        #____________________________________________________________________________________________________________________
            
            
            
        
        # run decile for each market cap range within the period
        #____________________________________________________________________________________________________________________
        
        for cap_key in range(len(cap_range)-1):
       
            lower_cap = cap_range[cap_key]
            upper_cap = cap_range[cap_key+1]
        
 
            is_big_cap = (Mkt_by_decades >= lower_cap) & (Mkt_by_decades < upper_cap)
 
            stoch_values_big_cap = Stoch_by_decades[is_big_cap].values.flatten()
            stoch_values_big_cap = stoch_values_big_cap[~isnan(stoch_values_big_cap.tolist())]
            quantile_big_cap = np.percentile(stoch_values_big_cap,q=[0,10,20,30,40,50,60,70,80,90]).tolist()
            quantile_big_cap.append(max_value)
            quantile_big_cap = list(set(quantile_big_cap))
            quantile_big_cap.sort()
 
            stoch_values_big_cap = None
 
            decile = pd.DataFrame(index=quantile_big_cap[:-1],columns=decile_col)
 
            for i in range(len(quantile_big_cap)-1):
                lowq = quantile_big_cap[i]
                highq = quantile_big_cap[i+1]
                buy = (Stoch_by_decades < highq) & (Stoch_by_decades >= lowq) & is_big_cap
                
                decile.loc[lowq,'#obs'] = buy.sum().sum()
                
                
                for day in move_days:
                    exec('decile.loc[lowq,\'' + day +'\'] = nanmean((Move' + day + '_by_decades[buy]).values)')

            
            

 
            decile = decile.sort_index(ascending=False)
            decile = decile.set_index([['>=' + str(x) for x in decile.index]])
            
            decile_dict[lower_cap][decades[dates_key]] = decile
            
            #____________________________________________________________________________________________________________________
            
            
            # All-time
            #____________________________________________________________________________________________________________________

            is_big_cap = (Mkt_Cap >= lower_cap) & (Mkt_Cap < upper_cap)

            stoch_values_big_cap = stoch_table[is_big_cap].values.flatten()
            stoch_values_big_cap = stoch_values_big_cap[~isnan(stoch_values_big_cap.tolist())]
            quantile_big_cap = np.percentile(stoch_values_big_cap,q=[0,10,20,30,40,50,60,70,80,90]).tolist()
            quantile_big_cap.append(max_value)
            quantile_big_cap = list(set(quantile_big_cap))
            quantile_big_cap.sort()
            decile = pd.DataFrame(index=quantile_big_cap[:-1],columns=decile_col)



            for i in range(len(quantile_big_cap)-1):
                lowq = quantile_big_cap[i]
                highq = quantile_big_cap[i+1]
                buy = (stoch_table < highq) & (stoch_table >= lowq) & is_big_cap
                decile.loc[lowq,'#obs'] = buy.sum().sum()


                for day in move_days:
                    exec('decile.loc[lowq,\'' + day +'\'] = nanmean((Move[' + day + '][buy]).values)')


            decile = decile.sort_index(ascending=False)
            decile = decile.set_index([['>=' + str(x) for x in decile.index]])

            decile_dict[lower_cap][decades[-1]] = decile
            
            #____________________________________________________________________________________________________________________

        
        is_big_cap = None
        Stoch_by_decades = None
        Mkt_by_decades = None
        
        for day in move_days:
                exec('Move' + day + '_by_decades = None')
    
    # print deciles
    #____________________________________________________________________________________________________________________
    filename = (myDirect + '\deciles_' + str(window) + '_day_' + indicator_name +'.csv')
        
    with open(filename,'a') as my_file:
        my_file.writelines(str(window) + ' day ' + indicator_name + '\n')

    
    for cap_key in range(len(cap_range)-1):
        
        lower_cap = cap_range[cap_key]
        upper_cap = cap_range[cap_key+1]
        
        with open(filename,'a') as my_file:
            
            my_file.writelines('Market Cap ' + str(lower_cap) + '-' + str(upper_cap) + '\n')
            
            for decade in decades:
                my_file.writelines(decade + '\n')
                decile_dict[lower_cap][decade].to_csv(my_file)
                my_file.writelines('\n')
        #____________________________________________________________________________________________________________________